services:
  - type: web
    name: healthscript-advisor
    runtime: python3
    buildCommand: "pip install --upgrade pip && pip install --no-cache-dir -r requirements.txt"
    startCommand: "streamlit run app.py --server.port $PORT --server.headless true --server.runOnSave false"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.6
      - key: MYSQL_HOST
        value: your_mysql_host
      - key: MYSQL_USER
        value: your_mysql_user
      - key: MYSQL_PASSWORD
        value: your_mysql_password
      - key: MYSQL_DATABASE
        value: your_database
      - key: FIREBASE_CREDENTIALS_PATH
        value: docbuddy-ai-firebase-adminsdk-fbsvc-a2af6aaab6.json
      - key: GROQ_API_KEY
        value: your_groq_api_key
